spring:
  redis:
    host: 47.98.218.161
    port: 6379
    password: toortoor123
    #Redis数据库索引（默认为0）
    database: 0
    #连接超时时间（毫秒）
    #timeout: 18000
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        #最大阻塞等待时间(负数表示没限制)
        #max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 5
        #连接池中的最小空闲连接
        min-idle: 0
  datasource:
    username: root
    password: toortoor123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.218.161:3307/pd_auth?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml